call_parentheses = "Always"
collapse_simple_statement = "Never"
column_width = 120
indent_type = "Tabs"
line_endings = "Unix"
quote_style = "AutoPreferDouble"
space_after_function_names = "Never"
syntax = "All"
