package = "AoC-lua"
version = "0.0.0"
lua     = "5.4"

[description]
summary = ""
maintainer = "Yang Shen"
labels = [ "" ]
license = "MIT"

[dependencies]
md5 = "==1.3"
penlight = "==1.5"

[run]
args = [ "src/main.lua" ]

[build]
type = "builtin"
